# Generated by Django 5.1.1 on 2025-06-01 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ferremas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagotransferencia',
            name='comprobante',
        ),
    ]
