CREATE TABLE productos (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(255),
    descripcion VARCHAR2(1000),
    precio NUMBER,
    stock NUMBER,
    categoria VARCHAR2(255),
    marca VARCHAR2(255),
    imagen VARCHAR2(1000)
);
