CREATE TABLE usuarios (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(100) UNIQUE NOT NULL,
    email VARCHAR2(100) UNIQUE NOT NULL,
    hashed_password VARCHAR2(255) NOT NULL,
    rol VARCHAR2(50) DEFAULT 'cliente'
);

INSERT INTO usuarios (username, email, hashed_password, rol)
VALUES (
  'admin',
  'admin@ferremas.com',
  '$2b$12$eW5Qw7Qw9kQw7Qw7Qw7QwOeQw7Qw7Qw7Qw7Qw7Qw7Qw7Qw7Qw7Qw',
  'administrador'
);

CREATE TABLE productos (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(255),
    descripcion VARCHAR2(1000),
    precio NUMBER,
    stock NUMBER,
    categoria VARCHAR2(255),
    marca VARCHAR2(255),
    imagen VARCHAR2(1000)
);
